#
# SPDX-FileCopyrightText: Copyright 2022 Andreas Sandberg <andreas@sandberg.uk>
#
# SPDX-License-Identifier: 0BSD
#

---
name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wrt-arch:
          - arm_cortex-a7_neon-vfpv4-openwrt-21.02
          - aarch64_cortex-a53-openwrt-21.02
          - aarch64_cortex-a72-openwrt-21.02

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: openwrt/gh-action-sdk@v3
        env:
          ARCH: ${{ matrix.wrt-arch }}
          PACKAGES: gosolis luci-app-gosolis
          V: sc

      - name: Store logs
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.wrt-arch}}-logs
          path: logs/

      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.wrt-arch }}-packages
          path: bin/packages/**/*.ipk
